### ISSUE TITLE
Weird readings on interface index

### ISSUE THREAD

**Issue by hallowatcher** [rune-js/filestore#10]
So I was messing around with this project and the cache in general and noticed that the interface index (the 4th one) reads some strange data.

I looped through all the interfaces and dumped them into a JSON file: https://hwc.hr/i/c4Sm8j5m.json

If you do a search for `Blast Furnace Temp Gauge`, you can already see the weirdness I mean. The children of each interface might be the same? Also, the parent IDs are either 65535 (which in code get set to -1), or 7 as stated by Promises in the Discord.

I also compared a reading directly from the client, and even the first byte is different. (The first byte is the one that denotes the type)
![image](https://user-images.githubusercontent.com/6265839/112506841-6be56400-8d8e-11eb-92c0-91b5316b67a1.png)

Furthermore, the length of the children array seems to be fine, and correlates with the client decoding.
In this next screenshot, you can see the direct comparison of interface index 274:27 which should be the Cook's Assistant text.
![image](https://user-images.githubusercontent.com/6265839/112507096-a64f0100-8d8e-11eb-8cc3-937ad14a1a59.png)

The filestore thinks it's a ModelWidget, when in reality it should be a text widget (LinkWidget as defined in the project)

**Comment by Displee** [comment]
Side note: the `Blast Furnace Temp Gauge` component comes from `interface 30` `component 0`.

**Comment by hallowatcher** [comment]
I've figured it out!

It turns out the `decompress` function was taking its data from the global index instead of only for its own components. It's a bit hard to explain, but 1 line fixed it. The function `getArchive` already runs the `decodeArchiveFiles`, so whenever doing `getArchive`, everything would work.

BUT since the widget store does `get` and then checks if its either a file or an archive, it never runs `decodeArchiveFiles`. That means that the file content wasn't being set, and the internal if statement here:
![image](https://user-images.githubusercontent.com/6265839/112737607-0515a580-8f5c-11eb-8e3d-c8894737deb3.png)
was running `file.decompress`, which would get its data from the global widget index instead of only for its own subset of components.

I don't know what other stores this affects, but it definitely fixes widgets for good:
![image](https://user-images.githubusercontent.com/6265839/112737629-2a0a1880-8f5c-11eb-95a1-12787d315265.png)

You can find a full dumped json file here, it looks beautiful: https://hwc.hr/i/1LjntS8U.json

PR is at #11

**Comment by hallowatcher** [comment]
From all this research, I also found out that `parentId` is NOT reliable at all. I checked the client itself:
![image](https://user-images.githubusercontent.com/6265839/112739008-562b9680-8f68-11eb-8ed7-d3faad652f1d.png)

Which is also reflected in the JSON file I sent (showing widget 274:27 in this example):
![image](https://user-images.githubusercontent.com/6265839/112739156-3ef1a680-8f72-11eb-8aae-a45859fe2ce7.png)
